{% set name = "httptools" %}
{% set version = "0.0.11" %}
{% set sha256 = "04c7703bbef0e8ca28b09811547352b8c7c20549eab70dc24e536bb24fd2b7c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . -vvv"
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - httptools

about:
  home: https://github.com/MagicStack/httptools
  summary: "Fast HTTP parser"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
