{% set name = "httptools" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/MagicStack/httptools/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 20894c98b3fb19e498c520ec398f2c8f6967eee6ac56aa05b91edaca37c9e03d
    patches:
      - 101.patch
  - url: https://github.com/nodejs/http-parser/archive/2343fd6b5214b2ded2cdcf76de2bf60903bb90cd.tar.gz
    sha256: 23c94c21959a94fcd71f7bfb161700d0e06541a7bd238f88d8819e6087fd2117
    folder: vendor/http-parser
  - url: https://github.com/nodejs/llhttp/archive/caed04d6c1251e54c642bddfc7d0330af234f0d3.tar.gz
    sha256: 63d807120603090ebc3778f49963c7ce6b7bf068dbd1529d4d66b83653b32e03
    folder: vendor/llhttp

build:
  number: 1
  script: 
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython
  run:
    - python

test:
  imports:
    - httptools
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MagicStack/httptools
  summary: Fast HTTP parser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - carlodri
