{% set name = "httptools" %}
{% set version = "0.6.1" %}
{% set sha256 = "c6e26c30455600b95d94b1b836085138e82f177351454ee841c148f93a9bad5a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - httptools
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MagicStack/httptools
  summary: Fast HTTP parser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - carlodri
