appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ldybTX9y/Vazh8LoYKsixu5KYImzA8tj7HSKr3GzoOlmY5e6m8KpOz3abj1wXyqeZa2PSaS+KQzEl/vkOGE8KXAo25c6/jY4SxKsfUUeO4bCc+/umatZctpu0/LLVa83Y4ELRUIbhvtN4GJb4N4JoRAPdI2xaIPYnfDVoB1eSVTMtUyUoU5fDAuF2JWhGhXCTbPZHmPFXQxRCggMcq/MUGUGOE+HJ9caxa1/DdFP4HcTaDBXt73p+Zv7hXi4VzFgcW2/vVEiNT5OSDliicBvIy8NbJTbVslvonAgwoxalh94POSoMTpmgNWFt4kJSWn1VGshLpDVL5QnjKRRSubI52U/2VRBvkQJCzs3+5oKauCtSTFz6THr7EL0rK/1JQ0r8qhDY9MKDoDguS8JKziNV6UZe+5noqwvlEqPAMnUWHDhAstcZTmmEYbiNy4TAiYAquFxbNJJbafgsI6UrjfwKLinVTGHDGMNaPLYADJAuuKZVsnPuGJwuAwzkOCtXTwMruCFgSGsgRSU1D5IRhpTb5WHCasHiuQGXdnujy4xYlZrtZUDS2jZDOkTfOlliuRFAJNLcpBlKEJow9prH+jpXtABoH4FYAps4SEkvKAGIXgUeLUc5Z9Q45xiKLs40jeuHtnwAmLOi77vJySRCr2Qg1o5tFyog1kevpI4kWO76cc=}
